### ISSUE TITLE
Author sorting

### ISSUE THREAD

**Issue by jawalsh** [rshiggin/dh-abstracts#10]
In browse by author mode, the authors are sorted inconsistently, some sorting on first name, others on last. We want them consistently sorted by last name.

**Comment by rshiggin** [comment]
Resolved by pulling metadata fields from TEI (surname, forename format) rather than dc:meta (no format: names, email, institution jammed into one creator field), with changed setting in teiPreFilter.xsl. Running new index changes all creator/author calls to proper format.
